import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f9ff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    backgroundColor: Colors.white,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
  },
  content: {
    flex: 1,
  },
  spacer: {
    height: 40,
  },
  heroSection: {
    paddingHorizontal: 16,
    paddingVertical: 24,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: Colors.text,
    marginBottom: 12,
    lineHeight: 32,
  },
  heroSubtitle: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.textSecondary,
    marginBottom: 12,
    lineHeight: 20,
  },
  heroTag: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.sky,
    marginBottom: 16,
  },
  cta: {
    backgroundColor: Colors.sky,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: "center",
  },
  ctaText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
  },
  ctaPrimary: {
    backgroundColor: Colors.sky,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
  },
  ctaPrimaryText: {
    fontSize: 15,
    fontWeight: "800",
    color: Colors.white,
  },
  section: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    backgroundColor: Colors.white,
    borderRadius: 14,
    marginHorizontal: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
    marginBottom: 8,
  },
  sectionSubtitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.sky,
    marginBottom: 8,
  },
  sectionDescription: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textSecondary,
    marginBottom: 16,
    lineHeight: 18,
  },
  benefitsList: {
    gap: 12,
  },
  benefit: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  benefitText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    flex: 1,
  },
  stepsContainer: {
    gap: 16,
  },
  step: {
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  stepNumber: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  stepNumberText: {
    fontSize: 18,
    fontWeight: "900",
    color: Colors.sky,
  },
  stepTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 6,
  },
  stepDescription: {
    fontSize: 13,
    fontWeight: "500",
    color: Colors.textSecondary,
    lineHeight: 18,
  },
  earnBenefits: {
    gap: 12,
    marginBottom: 16,
  },
  earnBenefit: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  earnBenefitText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    flex: 1,
  },
  flowContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    gap: 8,
  },
  flowStep: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 12,
    backgroundColor: "#f0f9ff",
    borderRadius: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e0f2fe",
  },
  flowStepLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.sky,
    marginBottom: 4,
  },
  flowStepDesc: {
    fontSize: 11,
    fontWeight: "500",
    color: Colors.textSecondary,
    textAlign: "center",
  },
  discountBenefits: {
    gap: 12,
  },
  discountBenefit: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  discountBenefitText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    flex: 1,
  },
  teamBenefits: {
    gap: 12,
  },
  teamBenefit: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  teamBenefitText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    flex: 1,
  },
  supportItems: {
    gap: 12,
  },
  supportItem: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  supportItemText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    flex: 1,
  },
  audienceItems: {
    gap: 10,
    marginBottom: 16,
  },
  audienceItem: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  audienceBullet: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.sky,
    marginTop: 6,
  },
  audienceText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    flex: 1,
  },
  testimonial: {
    backgroundColor: "#f0f9ff",
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: Colors.sky,
    marginBottom: 16,
  },
  testimonialText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    fontStyle: "italic",
    lineHeight: 18,
  },
})

export default styles
