import { StyleSheet, Dimensions } from "react-native"
import { Colors } from "../constants/colors"
import { palette, radius, shadow } from "../theme/theme"

const SCREEN_HEIGHT = Dimensions.get("window").height
const VARIANT_MODAL_HEIGHT = SCREEN_HEIGHT * 0.75

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: palette.slate50,
  },
  headerBackground: {
    position: "relative",
    overflow: "hidden",
    borderBottomWidth: 1,
    minHeight: 90,
  },
  headerBackgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  headerContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.slate50,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.slate50,
    paddingHorizontal: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginTop: 8,
    textAlign: "center",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flex: 1,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: Colors.white,
    flex: 1,
    textAlign: "center",
  },
  selectAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  selectAllCheckbox: {
    width: 18,
    height: 18,
    borderRadius: 3,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  selectAllCheckboxChecked: {
    backgroundColor: Colors.sky,
    borderColor: Colors.sky,
  },
  selectAllText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  selectAllTextActive: {
    color: Colors.sky,
    fontWeight: "700",
  },
  listContent: {
    backgroundColor: palette.slate50,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 16,
    gap: 0,
  },
  rowBack: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  backLeftBtn: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 90,
  },
  backLeftBtnLeft: {
    backgroundColor: Colors.sky,
    left: 0,
  },
  backRightBtn: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 90,
  },
  backRightBtnRight: {
    backgroundColor: "#ef4444",
    right: 0,
  },
  cartActionInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  deleteActionInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  backTextWhite: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: "700",
  },
  cartItemContainer: {
    flexDirection: "row",
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 10,
    alignItems: "flex-start",
    position: "relative",
  },
  swipeRowContainer: {
    position: "relative",
    overflow: "hidden",
  },
  swipeAction: {
    position: "absolute",
    top: 0,
    bottom: 1,
    width: 132,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    zIndex: 0,
  },
  checkoutSwipeAction: {
    left: 0,
    backgroundColor: "#0ea5e9",
  },
  deleteSwipeAction: {
    right: 0,
    backgroundColor: Colors.error,
  },
  swipeActionText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    paddingHorizontal: 8,
  },
  containerGradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  containerSelected: {
    // Will be overridden by inline styles in JSX
  },
  checkbox: {
    padding: 4,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxBoxChecked: {
    backgroundColor: Colors.sky,
    borderColor: Colors.sky,
  },
  contentWrapper: {
    flex: 1,
    flexDirection: "row",
    gap: 10,
    zIndex: 1,
  },
  imageContainer: {
    position: "relative",
    width: 100,
    height: 100,
    borderRadius: radius.md,
    overflow: "hidden",
    backgroundColor: palette.slate200,
    flexShrink: 0,
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  discountBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    backgroundColor: "#ef4444",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  discountText: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: "700",
  },
  detailsContainer: {
    flex: 1,
    gap: 5,
    justifyContent: "space-between",
  },
  brand: {
    fontSize: 10,
    fontWeight: "600",
    color: Colors.textSecondary,
    textTransform: "uppercase",
  },
  brandNameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  productName: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text,
    lineHeight: 16,
  },
  variantQuantityRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  variantDropdown: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    borderWidth: 1,
    gap: 8,
  },
  variantDropdownContent: {
    flex: 1,
    gap: 3,
  },
  variantDropdownText: {
    fontSize: 12,
    fontWeight: "500",
    color: Colors.sky,
    lineHeight: 14,
  },
  quantityControlCompact: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  quantityBtnSmall: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderRadius: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityTextCompact: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.text,
    minWidth: 24,
    textAlign: "center",
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  priceQuantityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 2,
  },
  memberPrice: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.text,
  },
  srpPrice: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.textSecondary,
    textDecorationLine: "line-through",
  },
  badgeRow: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
  },
  pvBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 20,
  },
  pvText: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.white,
    letterSpacing: 0.2,
  },
  priceRemoveRow: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  quantityControl: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  quantityBtn: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.text,
    minWidth: 28,
    textAlign: "center",
  },
  itemPrice: {
    fontSize: 12,
    fontWeight: "800",
    color: Colors.sky,
    minWidth: 60,
    textAlign: "right",
  },
  removeBtn: {
    padding: 4,
  },
  footer: {
    borderTopWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerLeft: {
    flex: 0,
  },
  footerRight: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  totalSection: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    gap: 2,
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  totalPrice: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
    marginTop: 2,
  },
  checkoutBtn: {
    backgroundColor: Colors.sky,
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: radius.lg,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    flex: 1,
    ...shadow.sm,
  },
  checkoutBtnText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "700",
    flexShrink: 1,
  },
  headerGradient: {
    paddingTop: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
  },
  headerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  badge: {
    position: "absolute",
    top: -4,
    right: -6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.error,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: Colors.white,
  },
  badgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: Colors.white,
    lineHeight: 11,
  },
  swipeHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  swipeHintText: {
    fontSize: 10,
    letterSpacing: 0.3,
  },
  brandHeader: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: Colors.white,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
  },
  brandCheckbox: {
    padding: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  brandHeaderContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandHeaderText: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  modalOverlay: {
    flex: 1,
  },
  variantModal: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: VARIANT_MODAL_HEIGHT,
    width: "100%",
    paddingBottom: 20,
    overflow: "hidden",
  },
  variantModalHandleContainer: {
    alignItems: "center",
    paddingVertical: 12,
  },
  variantModalHandle: {
    width: 48,
    height: 5,
    borderRadius: 2.5,
  },
  variantModalHeader: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 0.5,
    alignItems: "flex-start",
  },
  variantModalTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
  },
  variantLoadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  variantList: {
    flex: 1,
    paddingHorizontal: 0,
  },
  variantItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 0.5,
  },
  variantItemLast: {
    borderBottomWidth: 0,
  },
  variantThumbnail: {
    width: 56,
    height: 56,
    borderRadius: radius.md,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  variantThumbnailImage: {
    width: "100%",
    height: "100%",
  },
  variantColorBox: {
    width: 48,
    height: 48,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  variantItemContent: {
    flex: 1,
  },
  variantItemName: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.text,
    marginBottom: 4,
  },
  variantItemDetails: {
    fontSize: 13,
    fontWeight: "400",
    color: Colors.textSecondary,
    marginBottom: 8,
  },
  variantItemPrice: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.sky,
  },
  variantCheckmark: {
    marginLeft: 20,
    flexShrink: 0,
  },
})

export default styles
