import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    position: "relative",
    overflow: "hidden",
    minHeight: 100,
    borderBottomWidth: 1,
  },
  headerBackgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  headerContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: -12,
  },
  headerInfo: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerGreeting: {
    fontSize: 17,
    fontWeight: "800",
  },
  headerSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  content: {
    flex: 1,
    paddingHorizontal: 0,
    gap: 0,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyText: {
    fontSize: 14,
  },
  section: {
    padding: 14,
    marginHorizontal: 0,
    width: "100%",
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
  },
  itemCard: {
    flexDirection: "row",
    gap: 12,
    padding: 14,
    borderWidth: 1,
  },
  shopHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  shopInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  shopName: {
    fontSize: 13,
    fontWeight: "600",
  },
  viewBrandContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  viewBrandText: {
    fontSize: 12,
    fontWeight: "500",
  },
  itemImage: {
    width: 100,
    height: 100,
    borderRadius: 6,
    backgroundColor: "#f0f0f0",
  },
  itemDetails: {
    flex: 1,
    justifyContent: "space-between",
  },
  itemName: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 2,
  },
  itemVariantInfo: {
    fontSize: 10,
    marginTop: 2,
  },
  itemFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  itemPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  itemPrice: {
    fontSize: 13,
    fontWeight: "700",
  },
  itemPriceSrp: {
    fontSize: 11,
    textDecorationLine: "line-through",
  },
  itemQty: {
    fontSize: 11,
  },
  paymentList: {
    gap: 10,
  },
  paymentListItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  paymentGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  paymentGridItem: {
    width: "100%",
  },
  paymentGridCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderRadius: 0,
    borderWidth: 0,
    minHeight: 50,
    gap: 10,
  },
  paymentGridLogo: {
    width: 36,
    height: 36,
    borderRadius: 6,
  },
  paymentGridNameContainer: {
    flex: 1,
    marginRight: 8,
  },
  paymentGridName: {
    fontSize: 12,
    fontWeight: "600",
  },
  paymentGridSubtitle: {
    fontSize: 10,
    fontWeight: "400",
    marginTop: 2,
  },
  paymentBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    backgroundColor: Colors.sky,
  },
  paymentBadgeText: {
    fontSize: 9,
    fontWeight: "600",
    color: Colors.white,
  },
  paymentGridCheckmark: {
    position: "absolute",
    top: 6,
    right: 6,
  },
  paymentCircleCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#d1d5db",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  paymentCircleCheckboxSelected: {
    borderColor: Colors.sky,
    backgroundColor: Colors.sky,
  },
  paymentListContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  paymentListName: {
    fontSize: 13,
    fontWeight: "500",
  },
  paymentLogo: {
    width: 40,
    height: 40,
    borderRadius: 6,
  },
  circleCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#d1d5db",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  circleCheckboxSelected: {
    borderColor: Colors.sky,
    backgroundColor: Colors.sky,
  },
  paymentDetailsLabel: {
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 12,
  },
  methodCard: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  methodContent: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  methodName: {
    fontSize: 13,
    fontWeight: "600",
  },
  methodDays: {
    fontSize: 11,
  },
  methodPrice: {
    fontSize: 13,
    fontWeight: "700",
  },
  radioButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 0.5,
  },
  voucherInputContainer: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  voucherInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  applyVoucherButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  applyVoucherButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.white,
  },
  voucherList: {
    gap: 10,
  },
  voucherCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
  },
  voucherContent: {
    flex: 1,
  },
  voucherCode: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
  },
  voucherDesc: {
    fontSize: 11,
  },
  removeVoucherText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ef4444",
  },
  noVouchersText: {
    fontSize: 13,
    fontWeight: "500",
    textAlign: "center",
    paddingVertical: 16,
  },
  priceLabel: {
    fontSize: 12,
    fontWeight: "500",
  },
  priceValue: {
    fontSize: 13,
    fontWeight: "600",
  },
  priceDisplayFlex: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  priceValueSrp: {
    fontSize: 11,
    textDecorationLine: "line-through",
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: "700",
  },
  totalPrice: {
    fontSize: 16,
    fontWeight: "800",
  },
  footer: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  footerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  footerPrice: {
    alignItems: "flex-end",
  },
  footerPriceLabel: {
    fontSize: 11,
    fontWeight: "500",
    marginBottom: 2,
  },
  footerPriceValue: {
    fontSize: 16,
    fontWeight: "800",
  },
  placeOrderBtn: {
    height: 48,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 16,
  },
  placeOrderBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 30,
    gap: 8,
  },
  loadingText: {
    fontSize: 12,
  },
  shippingHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  shippingHeaderInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  shippingTitle: {
    fontSize: 13,
    fontWeight: "600",
  },
  shippingContent: {
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  viewShippingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  viewShippingText: {
    fontSize: 12,
    fontWeight: "500",
  },
  addressEditBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  addressCard: {
    padding: 12,
    borderWidth: 1,
    marginBottom: 10,
  },
  addressCardCompact: {
    padding: 10,
    borderWidth: 1,
  },
  addressNameCompact: {
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 2,
  },
  addressTextCompact: {
    fontSize: 11,
    lineHeight: 14,
  },
  addressType: {
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  addressName: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 6,
    lineHeight: 16,
  },
  addressPhone: {
    fontSize: 11,
  },
  addressText: {
    fontSize: 11,
    lineHeight: 15,
    marginBottom: 6,
  },
  addressNotes: {
    fontSize: 10,
    fontStyle: "italic",
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999,
  },
  addressModal: {
    width: "90%",
    borderRadius: 16,
    maxHeight: "75%",
    borderWidth: 1,
    overflow: "hidden",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: "700",
  },
  addressList: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  addressListItem: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  addressListContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  addressListType: {
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    marginBottom: 2,
  },
  addressListName: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
    lineHeight: 16,
  },
  addressListPhone: {
    fontSize: 11,
  },
  addressListAddress: {
    fontSize: 11,
    lineHeight: 15,
  },
  shippingInfoContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    gap: 6,
  },
  shippingInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    marginTop: 10,
    marginBottom: 10,
  },
  shippingDetail: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 8,
  },
  shippingLabel: {
    fontSize: 11,
    marginBottom: 2,
  },
  shippingCity: {
    fontSize: 12,
    fontWeight: "600",
  },
  shippingCost: {
    fontSize: 14,
    fontWeight: "700",
  },
  shippingOptionsSeparator: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  shippingOptionsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  shippingOptionTitle: {
    fontSize: 13,
    fontWeight: "600",
  },
  viewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  viewAllText: {
    fontSize: 12,
    fontWeight: "500",
  },
  shippingOptionsContainer: {
    gap: 10,
  },
  shippingOptionCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
  },
  optionContent: {
    flex: 1,
  },
  optionName: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 4,
  },
  optionDays: {
    fontSize: 11,
  },
  optionPrice: {
    fontSize: 13,
    fontWeight: "700",
    marginLeft: 12,
  },
  referrerCard: {
    padding: 12,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  referrerUsername: {
    fontSize: 13,
    fontWeight: "600",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  overlayLoadingContainer: {
    borderRadius: 12,
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 200,
  },
  overlayLoadingText: {
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
})

export default styles
