import { Dimensions, StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

export const BANNER_HEIGHT = 190
export const SCREEN_WIDTH = Dimensions.get("window").width

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f5f5" },
  content: { paddingHorizontal: 8, paddingTop: 8, paddingBottom: 28, gap: 8 },
  loadingWrap: { paddingVertical: 42, alignItems: "center", gap: 10 },
  loadingText: { fontSize: 13, color: Colors.textSecondary },
  bannerShell: {
    gap: 10,
  },
  banner: {
    height: BANNER_HEIGHT,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#0f172a",
    padding: 18,
    marginRight: 12,
    justifyContent: "space-between",
    position: "relative",
  },
  bannerGlow: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    top: -80,
    right: -70,
    opacity: 0.22,
  },
  bannerTextWrap: {
    zIndex: 2,
    flex: 1,
    justifyContent: "center",
    paddingRight: 90,
  },
  bannerEyebrow: {
    fontSize: 11,
    fontWeight: "800",
    color: "rgba(255,255,255,0.75)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  bannerTitle: {
    fontSize: 24,
    lineHeight: 28,
    fontWeight: "900",
    color: Colors.white,
    marginTop: 8,
  },
  bannerSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: "rgba(255,255,255,0.84)",
    marginTop: 8,
  },
  bannerVideo: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 24,
  },
  videoOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    borderRadius: 24,
  },
  bannerIcon: {
    position: "absolute",
    right: 18,
    bottom: 18,
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.9)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
  },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: "#cbd5e1",
  },
  dotActive: {
    width: 20,
    backgroundColor: Colors.sky,
  },
  section: { gap: 0, paddingHorizontal: 4 },
  rankingBadgeSection: {
    flexDirection: "column",
    paddingHorizontal: 8,
    paddingTop: 0,
    paddingBottom: 10,
    marginBottom: 0,
    borderBottomWidth: 0.5,
    gap: 12,
  },
  memberCard: {
    width: "100%",
    maxWidth: "100%",
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  rankingBadgeWrapper: {
    width: 70,
    height: 70,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  rankingBadgeImage: {
    width: 70,
    height: 70,
    borderRadius: 12,
    resizeMode: "contain" as any,
  },
  memberInfo: {
    flex: 1,
    gap: 2,
  },
  memberLabel: {
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  rankingBadgeName: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
  },
  rankingBadgeSubtext: {
    fontSize: 13,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  badgeLogoContainer: {
    position: "absolute",
    right: -26,
    top: "50%",
    marginTop: -59,
    opacity: 0.15,
  },
  badgeLogo: {
    width: 100,
    height: 100,
    borderRadius: 8,
  },
  quickActionRow: {
    width: "100%",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 0,
  },
  quickActionCard: {
    flex: 1,
    maxWidth: "100%",
    borderRadius: 14,
    borderWidth: 1,
    overflow: "hidden",
  },
  quickActionGradient: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  quickActionTitle: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 13,
  },
  quickActionSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 11,
    fontWeight: "600",
  },
  statsBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0f9ff",
    marginHorizontal: -8,
    marginBottom: 0,
    borderBottomWidth: 0.5,
    borderBottomColor: "#e0f2fe",
  },
  statsItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    gap: 4,
    borderWidth: 0.25,
    borderColor: "#e5e7eb",
    backgroundColor: Colors.white,
  },
  statsMain: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statsValue: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.text,
  },
  statsLabel: {
    fontSize: 8,
    fontWeight: "700",
    color: Colors.textSecondary,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  sectionEven: {
    backgroundColor: "#f0f9ff",
    marginHorizontal: -8,
    paddingHorizontal: 8,
    paddingVertical: 18,
    gap: 0,
  },
  sectionOdd: {
    backgroundColor: "#f8fbff",
    marginHorizontal: -8,
    paddingHorizontal: 8,
    paddingVertical: 18,
    gap: 0,
  },
  sectionFeatured: {
    backgroundColor: "#f0f9ff",
    marginHorizontal: -8,
    paddingHorizontal: 8,
    paddingTop: 16,
    paddingBottom: 44,
    marginBottom: -28,
    gap: 10,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: "800", color: Colors.text },
  sectionMeta: { fontSize: 12, color: Colors.textSecondary, fontWeight: "600" },
  sectionAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  circleRow: {
    gap: 12,
    paddingRight: 4,
  },
  categoryGrid: {
    gap: 16,
  },
  roomGrid: {
    gap: 0,
  },
  circleItem: {
    width: 88,
    alignItems: "center",
    gap: 8,
    marginRight: 12,
  },
  categoryCircleItem: {
    width: 88,
    alignItems: "center",
    gap: 8,
    marginRight: 12,
  },
  categoryBadge: {
    position: "absolute",
    top: -2,
    right: -4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#ffffff",
    zIndex: 10,
  },
  categoryBadgeDark: {
    borderColor: "#111827",
  },
  categoryBadgeText: {
    color: "#ffffff",
    fontSize: 8,
    fontWeight: "bold",
  },
  roomItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    borderWidth: 0.5,
    borderColor: "#e5e7eb",
  },
  roomCircleContainer: {
    position: "relative",
    width: 64,
    height: 64,
  },
  roomBadge: {
    position: "absolute",
    top: -2,
    right: -6,
    backgroundColor: "#3b82f6",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#ffffff",
    zIndex: 10,
  },
  roomBadgeDark: {
    borderColor: "#111827",
  },
  roomBadgeText: {
    color: "#ffffff",
    fontSize: 8,
    fontWeight: "bold",
  },
  circleImageWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    padding: 3,
    backgroundColor: Colors.white,
  },
  roomCircleWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "#e0f2fe",
  },
  roomImage: {
    width: "100%",
    height: "100%",
  },
  roomCircleFallback: {
    width: "100%",
    height: "100%",
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
  },
  circleImage: {
    width: "100%",
    height: "100%",
    borderRadius: 36,
  },
  categoryCircle: {
    backgroundColor: "#eff6ff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowOffset: { width: 0, height: 0 },
    elevation: 0,
  },
  circleLabel: {
    fontSize: 12,
    textAlign: "center",
    color: Colors.text,
    fontWeight: "700",
    lineHeight: 16,
  },
  brandRowHorizontal: {
    paddingLeft: 8,
    paddingRight: 8,
  },
  brandSeparator: {
    width: 14,
  },
  brandCard: {
    width: 210,
    height: 200,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  brandLogoContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  brandLogoImage: {
    width: "100%",
    height: "100%",
  },
  brandLogoFallback: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  brandFallbackInitialLarge: {
    fontSize: 48,
    lineHeight: 52,
    fontWeight: "900",
    color: Colors.white,
  },
  brandLogoOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: "flex-start",
    justifyContent: "flex-end",
    height: "50%",
  },
  brandOverlayContent: {
    width: "100%",
    gap: 8,
    alignItems: "flex-start",
  },
  brandCardNameOverlay: {
    fontSize: 15,
    fontWeight: "900",
    textAlign: "left",
    letterSpacing: -0.2,
  },
  brandProductCountOverlay: {
    fontSize: 12,
    fontWeight: "600",
    color: "rgba(255,255,255,0.95)",
  },
  brandProductBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  brandCardImage: {
    width: "100%",
    height: "100%",
  },
  brandFallback: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dbeafe",
  },
  brandFallbackInitial: {
    fontSize: 34,
    lineHeight: 38,
    fontWeight: "900",
    color: Colors.sky,
  },
  brandCardOverlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(15,23,42,0.34)",
  },
  brandCardName: {
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
  },
  brandProductCount: {
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 2,
  },
  brandImagesGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  brandMiniImageContainer: {
    width: "33.33%",
    height: "50%",
    overflow: "hidden",
    borderWidth: 0.25,
  },
  brandMiniImage: {
    width: "100%",
    height: "100%",
  },
  brandMiniFallback: {
    backgroundColor: "#f1f5f9",
  },
  brandNamePlate: {
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderTopWidth: 0.5,
    borderTopColor: "rgba(0,0,0,0.05)",
  },
  featuredProductsContainer: {
    gap: 8,
  },
  masonryGrid: {
    flexDirection: "row",
    gap: 6,
  },
  masonryColumn: {
    flex: 1,
    gap: 8,
  },
  featuredProductItem: {
    width: "100%",
  },
  sampleAdCard: {
    width: "100%",
    height: 160,
    borderRadius: 12,
    overflow: "hidden",
  },
  sampleAdGradient: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    gap: 6,
  },
  sampleAdTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.white,
    textAlign: "center",
  },
  sampleAdSubtitle: {
    fontSize: 12,
    color: "rgba(255,255,255,0.9)",
    textAlign: "center",
  },
  sampleAdBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.3)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  sampleAdBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.white,
    textTransform: "uppercase",
  },
  featuredProductSkeleton: {
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    height: 280,
    overflow: "hidden",
  },
  noProductsText: {
    fontSize: 14,
    color: Colors.textSecondary,
    textAlign: "center",
    paddingVertical: 20,
  },
  marketingCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 0.5,
    minWidth: 110,
    flexShrink: 0,
  },
  marketingContent: {
    flex: 1,
    gap: 2,
  },
  marketingTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text,
  },
  marketingSubtitle: {
    fontSize: 10,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  recommendationsLoading: {
    paddingVertical: 32,
    alignItems: "center",
    gap: 8,
  },
  productGrid: {
    gap: 8,
  },
  emptyState: {
    paddingVertical: 32,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    gap: 8,
  },
  emptyStateText: {
    fontSize: 14,
    fontWeight: "600",
  },
  emptyStateSubtext: {
    fontSize: 12,
    textAlign: "center",
  },

})

export default styles
