import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#000",
  },
  overlay: {
    ...StyleSheet.absoluteFill,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  container: {
    flex: 1,
    justifyContent: "flex-end",
  },
  spacer: {
    flex: 1,
  },
  gradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "70%",
    zIndex: 1,
  },
  contentSection: {
    paddingHorizontal: 24,
    gap: 24,
    zIndex: 2,
  },
  homeLogoImage: {
    width: 50,
    height: 50,
  },
  logoWithTextRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  homeLogoText: {
    fontSize: 24,
    fontWeight: "600",
    color: Colors.white,
    marginTop: 6,
  },
  textWithLogoSection: {
    flexDirection: "column",
    alignItems: "flex-start",
    marginBottom: 24,
  },
  sideLogoImage: {
    width: 48,
    height: 48,
    opacity: 0.6,
    marginBottom: -15,
    backgroundColor: "transparent",
  },
  headingSection: {
    gap: 4,
    alignItems: "flex-start",
    marginTop: -5,
  },
  heading: {
    fontSize: 28,
    fontWeight: "700",
    fontStyle: "italic",
    color: Colors.white,
    letterSpacing: 0.2,
    textAlign: "left",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  subheading: {
    fontSize: 18,
    fontWeight: "400",
    fontStyle: "italic",
    color: "rgba(255, 255, 255, 0.9)",
    lineHeight: 18,
    textAlign: "left",
  },
  buttonSection: {
    gap: 12,
    marginTop: -16,
  },
  loginButton: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: Colors.sky,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  loginButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },
  googleButton: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },

  disabledButton: {
    opacity: 0.6,
  },
  buttonLoader: {
    marginRight: 4,
  },
  googleButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },
  passkeyButton: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  passkeyButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },
  howToEarnSection: {
    alignItems: "center",
    justifyContent: "center",
  },
  howToEarnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ff9500",
    textDecorationLine: "underline",
  },
  footerLinksRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.2)",
  },
  footerBullet: {
    fontSize: 12,
    color: "rgba(255, 255, 255, 0.5)",
  },
  whatIsAfHomeSection: {
    alignItems: "center",
    justifyContent: "center",
  },
  whatIsAfHomeText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ff9500",
    textDecorationLine: "underline",
  },
  signupLinkSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  signupText: {
    fontSize: 14,
    fontWeight: "500",
    color: "rgba(255, 255, 255, 0.8)",
  },
  signupLink: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
    textDecorationLine: "underline",
  },
  footerSection: {
    marginTop: 8,
  },
  footerText: {
    fontSize: 12,
    fontWeight: "400",
    color: "rgba(255, 255, 255, 0.7)",
    textAlign: "center",
    lineHeight: 18,
  },
  footerLink: {
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.9)",
    textDecorationLine: "underline",
  },
  biometricButton: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 24,
    backgroundColor: "#f97316",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 4,
  },
  biometricButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
  },

  separatorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginVertical: 6,
  },
  separatorLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.35)",
  },
  separatorOrContainer: {
    width: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  separatorOrText: {
    color: "rgba(255, 255, 255, 0.65)",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "lowercase",
  },
})

export default styles
