import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"
import { radius } from "../theme/theme"

const styles = StyleSheet.create({
  container: { flex: 1 },
  headerBackground: {
    position: "relative",
    overflow: "hidden",
    minHeight: 0,
  },
  headerDecor1: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    top: -40,
    right: -30,
  },
  headerDecor2: {
    position: "absolute",
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    bottom: 10,
    left: -20,
  },
  headerDecor3: {
    position: "absolute",
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    top: 40,
    left: "50%",
    marginLeft: -30,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingBottom: 0,
    height: 72,
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: "center",
  },
  backBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  menuBtn: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.white,
    textAlign: "center",
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: "600",
    color: "rgba(255,255,255,0.85)",
    textAlign: "center",
    marginTop: 2,
  },
  scrollContent: {
    flex: 1,
    paddingTop: 0,
    paddingBottom: 20,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  topThreeContainer: {
    borderRadius: 0,
    marginTop: -34,
    paddingHorizontal: 12,
    paddingTop: 100,
    paddingBottom: 20,
  },
  topThreeOverlap: {
    marginHorizontal: 0,
    paddingBottom: 28,
  },
  topThreeGrid: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    width: "100%",
  },
  topCardWrapper: {
    alignItems: "center",
    maxWidth: 112,
  },
  avatarContainer: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  crownContainer: {
    position: "absolute",
    top: -12,
    zIndex: 20,
  },
  crownEmoji: {
    fontSize: 28,
  },
  rankBadge: {
    position: "absolute",
    bottom: -8,
    right: -8,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: Colors.white,
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  rankBadgeText: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: "900",
  },
  topCardBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 8,
    minWidth: 58,
    justifyContent: "center",
    backgroundColor: "rgba(15, 23, 42, 0.36)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
  },
  topCardBadgeText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 11,
  },
  topCardAvatarOuter: {
    overflow: "hidden",
    borderWidth: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  topCardAvatarImageWrap: {
    width: "84%",
    height: "84%",
    borderRadius: 999,
    overflow: "hidden",
    borderWidth: 2,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  topCardAvatarImage: {
    width: "100%",
    height: "100%",
    alignSelf: "center",
  },
  topCardInitialCircle: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  topCardInitialRing: {
    width: "88%",
    height: "88%",
    borderRadius: 999,
    padding: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  topCardInitialInner: {
    width: "100%",
    height: "100%",
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  topCardInitial: {
    fontWeight: "900",
    textAlign: "center",
    includeFontPadding: false,
    textAlignVertical: "center",
    lineHeight: 18,
  },
  topCardName: {
    fontWeight: "800",
    textAlign: "center",
    fontSize: 14,
    lineHeight: 18,
    marginTop: 6,
    minHeight: 36,
    justifyContent: "center",
  },
  rankingsSection: {
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    marginTop: -20,
    marginHorizontal: 0,
    paddingBottom: 2,
  },
  sectionHeader: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    backgroundColor: "transparent",
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  sectionSubtitle: {
    marginTop: 3,
    fontSize: 11,
    lineHeight: 16,
  },
  rankingItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    backgroundColor: "transparent",
  },
  rankingItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  rankingBadge: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    overflow: "hidden",
  },
  rankingBadgeInner: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  rankingBadgeText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "900",
  },
  rankingAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    overflow: "hidden",
  },
  rankingAvatarFallback: {
    alignItems: "center",
    justifyContent: "center",
  },
  rankingAvatarImageWrap: {
    width: "84%",
    height: "84%",
    borderRadius: 999,
    overflow: "hidden",
    borderWidth: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  rankingAvatarImage: {
    width: "100%",
    height: "100%",
    alignSelf: "center",
  },
  rankingAvatarFallbackInner: {
    width: "86%",
    height: "86%",
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  rankingAvatarEmoji: {
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
    textAlignVertical: "center",
    includeFontPadding: false,
    lineHeight: 18,
  },
  rankingInfo: { gap: 2, flex: 1 },
  rankingName: {
    fontSize: 13,
    fontWeight: "800",
    flexShrink: 1,
  },
  rankingEarnings: {
    fontSize: 11,
    fontWeight: "600",
  },
  rankingMeta: {
    alignItems: "flex-end",
    marginLeft: 12,
  },
  rankingTrend: {
    fontSize: 11,
    fontWeight: "800",
  },
  rankingScore: {
    alignItems: "flex-end",
    marginLeft: 12,
    gap: 1,
  },
  rankingScoreRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  rankingScoreValue: {
    fontSize: 17,
    fontWeight: "900",
  },
  rankingScoreLabel: {
    fontSize: 10,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  currentUserContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#dbe7f3",
    backgroundColor: "#E0F2FE",
    marginVertical: 12,
    marginHorizontal: 12,
    borderRadius: 16,
  },
  currentUserContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  currentUserAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#0066FF",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#0066FF",
  },
  currentUserInitial: {
    color: Colors.white,
    fontSize: 16,
    fontWeight: "900",
  },
  currentUserInfo: {
    flex: 1,
  },
  currentUserLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0066FF",
  },
  currentUserRank: {
    fontSize: 14,
    fontWeight: "900",
    color: "#0369A1",
    marginTop: 2,
  },
  currentUserHighlight: {
    backgroundColor: "rgba(14,165,233,0.12)",
  },
  floatingUserIndicator: {
    position: "absolute",
    bottom: 20,
    left: "50%",
    marginLeft: -110,
    width: 220,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: Colors.sky,
    borderRadius: radius.full,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
    gap: 10,
  },
  floatingAvatarSection: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    gap: 10,
  },
  floatingUserAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.25)",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.6)",
  },
  floatingUserInitial: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "900",
  },
  floatingUserText: {
    flex: 1,
  },
  floatingUserName: {
    fontSize: 12,
    fontWeight: "800",
    color: Colors.white,
  },
  floatingUserRank: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.85)",
    marginTop: 2,
  },
})

export default styles
