import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#000" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  container: { flex: 1, justifyContent: "flex-end" },
  spacer: { flex: 1 },
  gradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "70%",
    zIndex: 1,
  },
  contentSection: {
    paddingHorizontal: 24,
    paddingBottom: 12,
    gap: 20,
    zIndex: 2,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 4,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  logoSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  homeLogoImage: {
    width: 50,
    height: 50,
  },
  homeLogoText: {
    fontSize: 24,
    fontWeight: "600",
    color: Colors.white,
    marginTop: 6,
  },
  headingSection: {
    gap: 4,
    alignItems: "flex-start",
  },
  heading: {
    fontSize: 28,
    fontWeight: "700",
    fontStyle: "italic",
    color: Colors.white,
    letterSpacing: 0.2,
    textAlign: "left",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  subheading: {
    fontSize: 18,
    fontWeight: "400",
    fontStyle: "italic",
    color: "rgba(255, 255, 255, 0.9)",
    lineHeight: 18,
    textAlign: "left",
  },
  scrollContent: {
    paddingBottom: 12,
  },
  fieldGroup: { marginBottom: 16 },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.9)",
    marginBottom: 6,
  },
  input: {
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    paddingHorizontal: 14,
    fontSize: 15,
    color: Colors.white,
  },
  emailRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    paddingLeft: 14,
    paddingRight: 12,
  },
  emailInput: { flex: 1, fontSize: 15, color: Colors.white },
  inputError: { borderColor: Colors.error },
  errorText: { fontSize: 12, color: "#ff6b6b", marginTop: 5, marginLeft: 2 },
  passwordRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    paddingLeft: 14,
    paddingRight: 12,
  },
  passwordInput: { flex: 1, fontSize: 15, color: Colors.white },
  signInBtn: { borderRadius: 10 },
  profileSection: {
    alignItems: "center",
    marginBottom: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.2)",
  },
  profilePicture: { width: 80, height: 80, borderRadius: 40, marginBottom: 12 },
  profilePictureDefault: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.sky,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  profilePictureDefaultText: {
    fontSize: 32,
    fontWeight: "800",
    color: Colors.white,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.white,
    marginBottom: 4,
  },
  profileEmail: { fontSize: 12, color: "rgba(255, 255, 255, 0.7)" },
  rememberMeRow: {
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  checkboxRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  checkboxChecked: { backgroundColor: Colors.sky, borderColor: Colors.sky },
  rememberMeText: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.9)",
    fontWeight: "500",
  },
  notYouButton: { marginTop: 16, paddingVertical: 12, alignItems: "center" },
  notYouText: { fontSize: 13, color: Colors.sky, fontWeight: "600" },
  signupLinkSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    marginTop: 16,
  },
  signupText: {
    fontSize: 14,
    fontWeight: "500",
    color: "rgba(255, 255, 255, 0.8)",
  },
  signupLink: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
    textDecorationLine: "underline",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 28,
    width: "100%",
    maxWidth: 340,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 8,
  },
  modalSubtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: 20,
    textAlign: "center",
  },
  modalPolling: { fontSize: 13, color: "#0ea5e9", marginBottom: 20 },
  otpInput: {
    width: "100%",
    height: 48,
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.inputBorder,
    borderRadius: 10,
    paddingHorizontal: 16,
    fontSize: 18,
    color: Colors.text,
    textAlign: "center",
    letterSpacing: 4,
    marginBottom: 16,
  },
  otpErrorText: {
    fontSize: 13,
    color: Colors.error,
    marginBottom: 12,
    textAlign: "center",
  },
  modalButton: { width: "100%", marginBottom: 8, borderRadius: 10, height: 48 },
  modalLink: { paddingVertical: 8 },
  modalLinkText: { color: "#0ea5e9", fontWeight: "600" },
})

export default styles
