import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.white,
  },
  scrollView: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  headerBackground: {
    position: "relative",
    overflow: "hidden",
    minHeight: 100,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  headerBackgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  headerContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 8,
  },
  headerIcon: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  headerInfo: {
    flex: 1,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
  },
  scrollContent: {
    padding: 0,
    paddingBottom: 40,
  },
  profileHeaderContainer: {
    borderRadius: 0,
    marginBottom: 0,
    overflow: "hidden",
    borderWidth: 0,
    borderColor: "#e5e7eb",
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  profileHeader: {
    alignItems: "center",
    gap: 16,
    paddingVertical: 24,
    paddingHorizontal: 16,
  },
  successIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#dcfce7",
    alignItems: "center",
    justifyContent: "center",
  },
  headerInfo: {
    alignItems: "center",
    gap: 8,
    flex: 1,
    width: "100%",
  },
  nameText: {
    fontSize: 24,
    fontWeight: "900",
    color: Colors.text,
    textAlign: "center",
  },
  usernameText: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.sky,
  },
  statusText: {
    fontSize: 12,
    fontWeight: "500",
    color: Colors.textSecondary,
    textAlign: "center",
  },
  section: {
    backgroundColor: Colors.white,
    borderRadius: 0,
    overflow: "hidden",
    marginBottom: 0,
    marginHorizontal: 0,
    borderWidth: 0,
    borderColor: "#e5e7eb",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: Colors.text,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#f9fafb",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  sectionContent: {
    padding: 16,
    gap: 12,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  infoLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  iconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  infoLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textSecondary,
    flex: 1,
  },
  infoValue: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
    flex: 1,
    textAlign: "right",
  },
  productRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 4,
    gap: 12,
  },
  productInfo: {
    flex: 1,
    gap: 4,
  },
  productName: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
  },
  productVariant: {
    fontSize: 11,
    fontWeight: "500",
    color: Colors.textSecondary,
  },
  productPriceContainer: {
    alignItems: "flex-end",
    gap: 2,
  },
  productPrice: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.sky,
  },
  productQty: {
    fontSize: 11,
    fontWeight: "500",
    color: Colors.textSecondary,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 4,
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  totalLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
  },
  totalPrice: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.sky,
  },
  footer: {
    paddingHorizontal: 12,
    paddingTop: 12,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    gap: 12,
  },
  payBtn: {
    flexDirection: "row",
    backgroundColor: Colors.sky,
    height: 52,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  payBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.white,
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  loadingContainer: {
    borderRadius: 12,
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    minWidth: 200,
  },
  loadingText: {
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    color: Colors.text,
    marginTop: 16,
  },
})

export default styles
