import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f8fbff" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(248, 251, 255, 0.72)",
  },
  safe: { flex: 1 },
  flex: { flex: 1 },
  scroll: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  card: {
    width: "100%",
    maxWidth: 820,
    backgroundColor: Colors.white,
    borderRadius: 18,
    padding: 24,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#e5e7eb",
    borderRadius: 14,
    padding: 4,
    marginBottom: 32,
  },
  tab: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: { backgroundColor: "#0ea5e9" },
  tabText: { fontSize: 15, fontWeight: "700", color: "#4b5563" },
  tabTextActive: { color: Colors.white },
  heading: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.text,
    marginBottom: 4,
  },
  subheading: { fontSize: 14, color: Colors.textSecondary, marginBottom: 26 },
  iconWrap: { alignItems: "center", marginBottom: 18 },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#dff3ff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#9bd8ff",
  },
  centerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.text,
    textAlign: "center",
  },
  centerSubtitle: {
    fontSize: 13,
    color: Colors.textSecondary,
    textAlign: "center",
    marginTop: 4,
  },
  emailText: {
    fontSize: 13,
    color: "#0ea5e9",
    textAlign: "center",
    marginTop: 4,
    fontWeight: "700",
  },
  codeRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 14,
    marginTop: 32,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  codeInput: {
    width: 56,
    height: 56,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: Colors.inputBorder,
    backgroundColor: Colors.white,
    fontSize: 22,
    fontWeight: "700",
    color: Colors.text,
  },
  messageText: { textAlign: "center", color: Colors.error, marginBottom: 12 },
  verifyBtn: { borderRadius: 10 },
  bottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 22,
    flexWrap: "wrap",
    gap: 10,
  },
  backText: { fontSize: 13, color: Colors.textSecondary },
  resendText: { fontSize: 13, color: "#0ea5e9" },
  resendDisabled: { color: Colors.textSecondary },
})

export default styles
