import { StyleSheet, Dimensions } from "react-native"
import { Colors } from "../constants/colors"

const SCREEN_WIDTH = Dimensions.get("window").width

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  animatedHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
  },
  scrollHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  scrollHeaderBackBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  scrollHeaderTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    marginHorizontal: 12,
  },
  scrollHeaderActions: {
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
  },
  loadingWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  errorText: {
    fontSize: 14,
    color: Colors.textSecondary,
  },
  scrollContent: {
    paddingBottom: 80, // Reduced padding for Buy Now button
  },
  galleryWrap: {
    width: SCREEN_WIDTH,
    minHeight: 300,
    maxHeight: SCREEN_WIDTH * 0.85,
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  galleryImageContainer: {
    width: SCREEN_WIDTH,
    minHeight: 300,
    maxHeight: SCREEN_WIDTH * 0.85,
    justifyContent: "center",
    alignItems: "center",
  },
  galleryImage: {
    width: SCREEN_WIDTH,
    height: "100%",
    minHeight: 300,
    maxHeight: SCREEN_WIDTH * 0.85,
  },
  galleryFallback: {
    width: SCREEN_WIDTH,
    minHeight: 300,
    maxHeight: SCREEN_WIDTH * 0.85,
    alignItems: "center",
    justifyContent: "center",
  },
  galleryPageCounter: {
    position: "absolute",
    bottom: 12,
    right: 12,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
  },
  galleryPageCounterText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.3,
  },
  galleryBackBtn: {
    position: "absolute",
    top: 0,
    left: 0,
    padding: 12,
  },
  galleryBackBtnInner: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  galleryTopRightIcons: {
    position: "absolute",
    top: 0,
    right: 0,
    padding: 12,
    flexDirection: "row",
    gap: 8,
  },
  galleryIconBtn: {
    padding: 0,
  },
  galleryIconBtnInner: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  discountBadge: {
    position: "absolute",
    top: 80,
    left: 12,
    backgroundColor: "rgba(239, 68, 68, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    maxWidth: SCREEN_WIDTH - 24,
  },
  discountBadgeText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
  discountMessage: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: "500",
    marginTop: 2,
  },
  soldRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  soldText: {
    fontSize: 12,
    color: Colors.textSecondary,
  },
  productName: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
    lineHeight: 24,
  },
  badgesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 12,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: Colors.white,
    letterSpacing: 0.2,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  currentPrice: {
    fontSize: 22,
    fontWeight: "800",
    color: Colors.sky,
  },
  originalPrice: {
    fontSize: 15,
    color: Colors.textSecondary,
    textDecorationLine: "line-through",
  },
  relatedSection: {
    paddingHorizontal: 8,
    paddingTop: 16,
    paddingBottom: 8,
    gap: 12,
  },
  relatedHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 0,
  },
  relatedTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.text,
  },
  relatedScroll: {
    paddingHorizontal: 0,
  },
  relatedRow: {
    flexDirection: "row",
    gap: 8,
  },
  relatedCard: {
    width: 220,
    height: 380, // Increased height to accommodate tallest item
  },
  priceAndBadgesSection: {
    paddingHorizontal: 8,
    paddingVertical: 12,
    gap: 12,
  },
  priceCard: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    gap: 12,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  priceContent: {
    flex: 1,
    gap: 8,
  },
  priceLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  priceDisplayRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  },
  discountBadgeSmall: {
    backgroundColor: "#fef2f2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#ef4444",
  },
  discountBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#ef4444",
  },
  soldInfoCard: {
    backgroundColor: "#f0f9ff",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: Colors.sky,
    minWidth: 80,
  },
  soldLabelSmall: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  soldCountSmall: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.sky,
  },
  badgesCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    gap: 12,
  },
  badgesLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  priceSoldContainer: {
    paddingHorizontal: 8,
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  nameSection: {
    paddingVertical: 8,
  },
  nameCard: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    gap: 12,
  },
  nameAndRatingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  productName: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
    lineHeight: 24,
    flex: 1,
  },
  ratingAndSoldRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "flex-end",
    flexShrink: 0,
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#fef3c7",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  ratingBadgeText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#92400e",
  },
  reviewCountText: {
    fontSize: 10,
    color: "#b45309",
    fontWeight: "500",
  },
  dividerDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#d1d5db",
  },
  soldBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  soldCountText: {
    fontSize: 11,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  sectionDivider: {
    height: 1,
    backgroundColor: "#e5e7eb",
  },
  detailsGrid: {
    gap: 12,
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 6,
  },
  detailContent: {
    flex: 1,
    gap: 2,
  },
  detailLabel: {
    fontSize: 11,
    color: Colors.textSecondary,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  detailValue: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.text,
  },
  trustSection: {
    gap: 10,
    marginTop: 4,
  },
  trustSectionTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 2,
  },
  trustGridRow: {
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  trustItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 8,
    backgroundColor: "#f9fafb",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  trustIconBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#f0f9ff",
    alignItems: "center",
    justifyContent: "center",
  },
  trustItemLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.text,
    textAlign: "center",
  },
  trustItemSubtext: {
    fontSize: 9,
    color: Colors.textSecondary,
    textAlign: "center",
    fontWeight: "500",
  },
  trustBadgeRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    gap: 0,
  },
  trustBadgeItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
  },
  trustBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.text,
  },
  trustBadgeDivider: {
    width: 1,
    height: 20,
    backgroundColor: "#e5e7eb",
  },
  guaranteesSection: {
    gap: 8,
    marginTop: 4,
  },
  guaranteeItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#f9fafb",
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#f97316",
  },
  guaranteeContent: {
    flex: 1,
    gap: 2,
  },
  guaranteeTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text,
  },
  guaranteeSubtext: {
    fontSize: 10,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  ratingSection: {
    paddingVertical: 8,
  },
  ratingCard: {
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
  },
  // New Shopee-style rating styles
  ratingSummaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  ratingScoreContainer: {
    alignItems: "center",
  },
  ratingScoreLarge: {
    fontSize: 48,
    fontWeight: "800",
    color: Colors.text,
    lineHeight: 56,
  },
  ratingStarsLarge: {
    flexDirection: "row",
    marginTop: 4,
    marginBottom: 8,
  },
  ratingStats: {
    alignItems: "flex-end",
    gap: 8,
  },
  ratingCount: {
    fontSize: 14,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  viewAllButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  viewAllText: {
    fontSize: 14,
    color: Colors.sky,
    fontWeight: "600",
  },
  ratingDistribution: {
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  ratingBarRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 12,
  },
  ratingBarLabel: {
    fontSize: 12,
    color: Colors.textSecondary,
    width: 24,
    textAlign: "right",
  },
  ratingBarTrack: {
    flex: 1,
    height: 8,
    backgroundColor: "#f3f4f6",
    borderRadius: 4,
    overflow: "hidden",
  },
  ratingBarFill: {
    height: "100%",
    backgroundColor: "#fbbf24",
    borderRadius: 4,
  },
  ratingBarCount: {
    fontSize: 12,
    color: Colors.textSecondary,
    width: 30,
    textAlign: "right",
  },
  reviewsSection: {
    marginTop: 8,
  },
  reviewsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  reviewsSectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
  },
  reviewsSectionCount: {
    fontSize: 16,
    color: Colors.textSecondary,
    marginLeft: 4,
  },
  reviewCard: {
    backgroundColor: "#f9fafb",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  reviewerInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  avatarContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#f3f4f6",
  },
  reviewAvatar: {
    width: 40,
    height: 40,
  },
  reviewerDetails: {
    flex: 1,
  },
  reviewCustomerName: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.text,
    marginBottom: 4,
  },
  reviewRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  reviewStars: {
    flexDirection: "row",
    gap: 1,
  },
  reviewRatingText: {
    fontSize: 12,
    color: Colors.textSecondary,
  },
  reviewDate: {
    fontSize: 12,
    color: Colors.textSecondary,
  },
  reviewComment: {
    fontSize: 14,
    color: Colors.text,
    lineHeight: 20,
  },
  reviewSeparator: {
    height: 1,
    backgroundColor: "#e5e7eb",
    marginTop: 12,
  },
  seeAllReviewsBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    marginTop: 8,
    gap: 8,
    backgroundColor: "#f0f9ff",
    borderRadius: 8,
  },
  seeAllReviewsBtnText: {
    fontSize: 14,
    color: Colors.sky,
    fontWeight: "600",
  },
  // No ratings state
  noRatingContainer: {
    alignItems: "center",
    paddingVertical: 32,
    gap: 16,
  },
  noRatingScore: {
    alignItems: "center",
    gap: 8,
  },
  noRatingText: {
    fontSize: 16,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  firstReviewButton: {
    backgroundColor: Colors.sky,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  firstReviewButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.white,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
  },
  variantsSection: {
    paddingVertical: 14,
    paddingHorizontal: 0,
  },
  variantsScrollView: {
    paddingHorizontal: 8,
  },
  variantsList: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  variantCard: {
    width: 90,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    overflow: "hidden",
    paddingBottom: 6,
  },
  variantCardSelected: {
    borderColor: Colors.sky,
    borderWidth: 2.5,
    shadowColor: Colors.sky,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  variantMediaContainer: {
    width: "100%",
    height: 80,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  variantImage: {
    width: "100%",
    height: "100%",
  },
  variantColorCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#e5e7eb",
  },
  variantPlaceholder: {
    justifyContent: "center",
    alignItems: "center",
  },
  variantCheckmark: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 12,
    padding: 2,
  },
  variantInfo: {
    paddingHorizontal: 6,
    paddingTop: 6,
    gap: 2,
  },
  variantLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.text,
  },
  variantSubInfo: {
    fontSize: 9,
    color: Colors.textSecondary,
    fontWeight: "400",
  },
  variantStock: {
    fontSize: 9,
    fontWeight: "500",
    marginTop: 2,
  },
  stockAvailable: {
    color: Colors.forest,
  },
  stockLow: {
    color: "#ef4444",
  },
  variantPrice: {
    fontSize: 0,
    display: "none",
  },
  variantDetailsCard: {
    marginHorizontal: 0,
    marginTop: 12,
    marginBottom: 0,
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    paddingVertical: 16,
    paddingHorizontal: 16,
    gap: 12,
  },
  variantDetailsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  variantDetailsTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
  },
  variantDetailsSku: {
    fontSize: 12,
    color: Colors.textSecondary,
    marginTop: 4,
  },
  variantPriceContainer: {
    alignItems: "flex-end",
  },
  variantPriceLarge: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.sky,
  },
  variantPriceOriginal: {
    fontSize: 12,
    color: Colors.textSecondary,
    textDecorationLine: "line-through",
    marginTop: 2,
  },
  variantDetailsGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    paddingVertical: 8,
  },
  detailGridItem: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 6,
    paddingVertical: 8,
    backgroundColor: "#f9fafb",
    borderRadius: 8,
    gap: 4,
  },
  detailGridLabel: {
    fontSize: 10,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  detailGridValue: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.text,
  },
  variantAdditionalInfo: {
    backgroundColor: "#f9fafb",
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 6,
    gap: 6,
  },
  infoPair: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  infoValue: {
    fontSize: 12,
    color: Colors.text,
    fontWeight: "500",
    flex: 1,
    textAlign: "right",
  },
  statusInStock: {
    color: Colors.forest,
    fontWeight: "700",
  },
  statusOutOfStock: {
    color: "#ef4444",
    fontWeight: "700",
  },
  actionButtonsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  addToCartText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.white,
  },
  descriptionsWrapper: {
    marginHorizontal: 0,
    marginVertical: 8,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    overflow: "hidden",
  },
  descriptionSection: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  descriptionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: "#f9fafb",
  },
  descriptionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
  },
  descriptionContent: {
    backgroundColor: Colors.white,
    overflow: "hidden",
  },
  descriptionContentInner: {
    padding: 12,
    gap: 16,
  },
  descriptionBlock: {
    gap: 8,
  },
  specificationsBlock: {
    gap: 8,
  },
  blockTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
    marginBottom: 8,
  },
  specificationsSection: {
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  specificationsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: "#f9fafb",
  },
  specificationsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
  },
  specificationsContent: {
    backgroundColor: Colors.white,
    overflow: "hidden",
  },
  specificationsContentInner: {
    padding: 12,
    gap: 12,
  },
  specRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  specLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textSecondary,
    flexShrink: 0,
  },
  specValue: {
    fontSize: 13,
    color: Colors.text,
    flex: 1,
    textAlign: "right",
  },
  brandSection: {
    paddingVertical: 8,
  },
  brandCard: {
    flexDirection: "row",
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    padding: 12,
    gap: 12,
    alignItems: "center",
  },
  brandLogo: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#f1f5f9",
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },
  brandInfo: {
    flex: 1,
    gap: 2,
  },
  brandHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  brandName: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
  },
  brandSupplier: {
    fontSize: 11,
    color: Colors.textSecondary,
  },
  brandStats: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 2,
  },
  brandStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  brandStatText: {
    fontSize: 11,
    color: Colors.textSecondary,
  },
  brandStatDivider: {
    width: 1,
    height: 12,
    backgroundColor: "#e5e7eb",
  },
  chatButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f0f9ff",
    alignItems: "center",
    justifyContent: "center",
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  onlineDotActive: {
    backgroundColor: Colors.forest,
  },
  onlineDotInactive: {
    backgroundColor: "#9ca3af",
  },
  // Buy Now Button Styles
  buyNowContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: 0,
  },
  decorativeIconContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
    paddingLeft: 2,
  },
  decorativeText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.sky,
    letterSpacing: 0.3,
  },
  priceDisplay: {
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#f3f4f6",
  },
  compactPriceText: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.text,
    lineHeight: 22,
  },
  priceLabelContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  priceIcon: {
    marginRight: 4,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    paddingHorizontal: 0,
  },
  addToCartButton: {
    width: 70,
    height: 52,
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
    backgroundColor: "#f97316",
    borderWidth: 1.5,
    borderColor: "#f97316",
    alignItems: "center",
    justifyContent: "center",
  },
  addToCartContent: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  addToCartText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.white,
    lineHeight: 13,
    textAlign: "center",
  },
  buyNowButtonContainer: {
    flex: 1,
    position: "relative",
  },
  buyNowButton: {
    backgroundColor: Colors.sky,
    height: 52,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  buyNowContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 16,
    gap: 8,
  },
  buyNowTextContainer: {
    flex: 1,
    justifyContent: "center",
  },
  buyNowTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
    letterSpacing: 0.3,
  },
  buyNowSubtitle: {
    fontSize: 11,
    fontWeight: "500",
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 2,
  },
  saveBadge: {
    position: "absolute",
    top: -12,
    right: 12,
    backgroundColor: "#f97316",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  saveBadgeText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: "700",
  },
  // Slideshow Image Viewer Styles
  slideshowOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#f8fafc",
    zIndex: 2000,
    flexDirection: "column",
  },
  slideshowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  slideshowCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    alignItems: "center",
    justifyContent: "center",
  },
  slideshowBrandInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 12,
  },
  slideshowBrandImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f1f5f9",
  },
  slideshowBrandText: {
    flex: 1,
  },
  slideshowBrandName: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
  },
  slideshowRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 2,
  },
  slideshowRating: {
    fontSize: 11,
    color: Colors.textSecondary,
    fontWeight: "600",
  },
  slideshowShareBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    alignItems: "center",
    justifyContent: "center",
  },
  slideshowImageWrapper: {
    flex: 1,
    position: "relative",
  },
  slideshowImageScroll: {
    flex: 1,
  },
  slideshowImageContainer: {
    width: SCREEN_WIDTH,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
    backgroundColor: Colors.white,
  },
  slideshowImage: {
    width: "90%",
    height: "85%",
    zIndex: 10,
  },
  slideshowPageIndicator: {
    position: "absolute",
    bottom: 12,
    alignSelf: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  slideshowPageText: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
  },
  slideshowProductCard: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 12,
    paddingTop: 12,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  slideshowCardContent: {
    flexDirection: "row",
    gap: 12,
  },
  slideshowCardImage: {
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
  },
  slideshowCardDetails: {
    flex: 1,
    justifyContent: "space-between",
  },
  slideshowCardName: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.text,
    lineHeight: 18,
  },
  slideshowCardPricing: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  slideshowCardPrice: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.sky,
  },
  slideshowCardOriginalPrice: {
    fontSize: 12,
    color: Colors.textSecondary,
    textDecorationLine: "line-through",
  },
  slideshowCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  slideshowCardMetaText: {
    fontSize: 11,
    color: Colors.textSecondary,
  },
  slideshowCardMetaRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 6,
  },
  slideshowVariantsSection: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  slideshowVariantsScroll: {
    marginHorizontal: -12,
    paddingHorizontal: 12,
  },
  slideshowVariantOption: {
    width: 60,
    height: 60,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    backgroundColor: "#f8fafc",
    overflow: "hidden",
  },
  slideshowVariantOptionSelected: {
    borderColor: Colors.sky,
    backgroundColor: Colors.sky,
  },
  slideshowVariantImage: {
    width: "100%",
    height: "100%",
  },
  slideshowVariantColor: {
    width: 44,
    height: 44,
    borderRadius: 8,
  },
  slideshowVariantCheck: {
    position: "absolute",
    bottom: -2,
    right: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.sky,
    alignItems: "center",
    justifyContent: "center",
  },
  slideshowVariantLabelText: {
    fontSize: 12,
    fontWeight: "500",
    color: Colors.textSecondary,
    marginTop: 4,
  },
  slideshowButtonRow: {
    flexDirection: "row",
    gap: 12,
    paddingBottom: 8,
  },
  slideshowAddToCartBtn: {
    flex: 0.4,
    borderWidth: 1.5,
    borderColor: Colors.sky,
    borderRadius: 10,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  slideshowAddToCartText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.sky,
  },
  slideshowBuyNowBtn: {
    flex: 0.6,
    backgroundColor: Colors.sky,
    borderRadius: 10,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  slideshowBuyNowText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.white,
  },
  // Buy Now Button Styles
  buyNowContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: 0,
  },
  buttonRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 0,
    paddingHorizontal: 0,
  },
  addToCartButton: {
    width: 70,
    height: 52,
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
    backgroundColor: "#f97316",
    borderWidth: 1.5,
    borderColor: "#f97316",
    alignItems: "center",
    justifyContent: "center",
  },
  addToCartContent: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  addToCartText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.white,
    lineHeight: 13,
    textAlign: "center",
  },
  buyNowButtonContainer: {
    flex: 1,
    position: "relative",
  },
  buyNowButton: {
    backgroundColor: Colors.sky,
    height: 52,
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  buyNowContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 16,
    gap: 8,
  },
  buyNowTextContainer: {
    flex: 1,
    justifyContent: "center",
  },
  buyNowTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.white,
    letterSpacing: 0.3,
  },
  buyNowSubtitle: {
    fontSize: 11,
    fontWeight: "500",
    color: "rgba(255, 255, 255, 0.85)",
    marginTop: 2,
  },
  saveBadge: {
    position: "absolute",
    top: -12,
    right: 12,
    backgroundColor: "#f97316",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  saveBadgeText: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: "700",
  },
  // New Shopee-style price section
  newPriceSection: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
    gap: 2,
  },
  bigPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
  },
  bigPrice: {
    fontSize: 32,
    fontWeight: "800",
  },
  strikethroughPrice: {
    fontSize: 14,
    textDecorationLine: "line-through",
  },
  discountBadgeNew: {
    backgroundColor: "#ef4444",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 3,
  },
  discountBadgeTextNew: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: "700",
  },
  socialProofRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  ratingSmall: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: "600",
  },
  socialProofDot: {
    fontSize: 12,
  },
  soldCountCompact: {
    fontSize: 12,
  },
  pvText: {
    fontSize: 12,
  },
  badgeChipsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  badgeChip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeChipText: {
    fontSize: 11,
    fontWeight: "600",
  },
  // Product name and brand section
  newNameSection: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  productNameNew: {
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 22,
    marginBottom: 6,
  },
  brandSkuRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  brandText: {
    fontSize: 12,
  },
  skuText: {
    fontSize: 12,
  },
  selectedVariantInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(0, 0, 0, 0.05)",
  },
  variantColorIndicator: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  selectedVariantText: {
    fontSize: 13,
    fontWeight: "500",
  },
  // Delivery section
  deliverySection: {
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  deliveryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  deliveryInfo: {
    flex: 1,
  },
  deliveryLabel: {
    fontSize: 13,
    fontWeight: "600",
  },
  deliveryDetails: {
    fontSize: 12,
    marginTop: 2,
  },
  // Compact variant info
  variantCompactInfo: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  variantCompactLabel: {
    fontSize: 12,
  },
  variantCompactPrice: {
    fontSize: 16,
    fontWeight: "700",
  },
  stockInStock: {
    color: Colors.forest,
    fontWeight: "600",
  },
  stockOutOfStock: {
    color: "#ef4444",
    fontWeight: "600",
  },
  youMayAlsoLikeSection: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 24,
    gap: 0,
    marginTop: -12,
  },
  youMayAlsoLikeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderBottomWidth: 1,
  },
  youMayAlsoLikeBorder: {
    flex: 1,
    height: 1,
  },
  youMayAlsoLikeTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: Colors.text,
  },
  youMayAlsoLikeMasonryGrid: {
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 8,
    paddingTop: 12,
    paddingBottom: 0,
  },
  youMayAlsoLikeMasonryColumn: {
    flex: 1,
    gap: 8,
  },
  youMayAlsoLikeItem: {
    width: "100%",
  },
  // Shopee-style variants bar (bottom of image)
  shopeeVariantsBar: {
    paddingVertical: 12,
    borderBottomWidth: 1,
  },
  shopeeVariantsScroll: {
    paddingHorizontal: 8,
  },
  shopeeVariantsContainer: {
    paddingHorizontal: 4,
    paddingRight: 12,
    gap: 8,
  },
  shopeeVariantItem: {
    width: 60,
    height: 60,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
    position: "relative",
    padding: 4,
    overflow: "hidden",
  },
  shopeeVariantItemSelected: {
    borderColor: Colors.sky,
    borderWidth: 1.5,
  },
  shopeeVariantColor: {
    width: 48,
    height: 48,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  shopeeVariantLabel: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 2,
  },
  shopeeVariantImage: {
    width: "100%",
    height: "100%",
    borderRadius: 6,
  },
  shopeeVariantText: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    paddingHorizontal: 4,
  },
  shopeeVariantSizeText: {
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  shopeeVariantCheck: {
    position: "absolute",
    bottom: -8,
    right: -8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: Colors.sky,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ffffff",
  },
})

export default styles
