import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"
import { radius, shadow } from "../theme/theme"

export const styles = StyleSheet.create({
  root: {
    flex: 1,
  },

  // ── Header (gradient hero with glass stats) ──
  headerBackground: {
    paddingBottom: 14,
    gap: 14,
    ...shadow.md,
  },
  heroStats: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 14,
    backgroundColor: "rgba(255,255,255,0.14)",
    borderRadius: radius.lg,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
  },
  heroStatCell: {
    flex: 1,
    alignItems: "center",
    gap: 3,
  },
  heroStatValue: {
    color: Colors.white,
    fontSize: 15,
    fontWeight: "800",
  },
  heroStatValueRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  heroStatLabel: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  heroStatDivider: {
    width: 1,
    height: 28,
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  headerBackgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 14,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 8,
    borderBottomWidth: 0,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    paddingRight: 8,
  },
  headerAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.18)",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.6)",
  },
  headerAvatarImg: {
    width: "100%",
    height: "100%",
  },
  headerAvatarInitial: {
    fontSize: 16,
    fontWeight: "800",
    color: Colors.white,
  },
  headerNameContainer: {
    flex: 1,
  },
  headerNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  headerName: {
    fontSize: 17,
    fontWeight: "800",
    color: Colors.text,
    flexShrink: 1,
  },
  profileIcon: {
    marginLeft: 4,
  },
  userBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: "rgba(255,255,255,0.22)",
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
    overflow: "hidden",
    height: 18,
  },
  badgeImageSmall: {
    width: 18,
    height: 18,
    borderRadius: 4,
  },
  userBadgeText: {
    fontSize: 9,
    fontWeight: "700",
    color: Colors.white,
  },
  usernameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 2,
  },
  usernameText: {
    fontSize: 12,
    color: Colors.sky,
    fontWeight: "600",
  },
  usernameDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#cbd5e1",
  },
  usernamePvText: {
    fontSize: 11,
    color: Colors.textSecondary,
    fontWeight: "600",
  },
  userRankText: {
    fontSize: 11,
    color: Colors.white,
    fontWeight: "700",
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
  },
  iconBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  badge: {
    position: "absolute",
    top: -4,
    right: -6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.error,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: Colors.white,
  },
  badgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: Colors.white,
    lineHeight: 11,
  },

  // ── Body (starts cleanly below the hero; scrolled cards clip at its edge) ──
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 10,
    gap: 10,
    paddingBottom: 20,
  },

  // ── Daily Check-In card ──
  checkinCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingVertical: 12,
    paddingHorizontal: 14,
    ...shadow.md,
  },
  checkinIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  checkinIcon: {
    width: 26,
    height: 26,
  },
  checkinInfo: {
    flex: 1,
    gap: 2,
  },
  checkinTitle: {
    fontSize: 14,
    fontWeight: "800",
  },
  checkinSub: {
    fontSize: 11,
    fontWeight: "500",
  },
  claimPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.sky,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.full,
  },
  claimPillText: {
    fontSize: 11,
    fontWeight: "800",
    color: Colors.white,
  },

  // ── Hero ──
  hero: {
    borderRadius: 20,
    alignItems: "center",
    paddingVertical: 28,
    paddingHorizontal: 16,
    gap: 6,
  },
  heroBubble: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255,255,255,0.25)",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: Colors.white,
    marginBottom: 4,
  },
  heroBubbleImg: {
    width: "100%",
    height: "100%",
  },
  heroBubbleInitial: {
    fontSize: 32,
    fontWeight: "800",
    color: Colors.white,
  },
  heroName: {
    fontSize: 20,
    fontWeight: "900",
    color: Colors.white,
  },
  heroEmail: {
    fontSize: 13,
    color: "rgba(255,255,255,0.8)",
    fontWeight: "500",
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  heroBadgeText: {
    fontSize: 11,
    color: Colors.white,
    fontWeight: "700",
  },

  // ── My Purchases ──
  purchasesHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  purchasesTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: Colors.text,
  },
  cardHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    flexShrink: 1,
  },
  cardHeaderChip: {
    width: 28,
    height: 28,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  purchasesViewAll: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  purchasesViewAllContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  purchasesViewAllText: {
    fontSize: 12,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  countBadge: {
    backgroundColor: Colors.error,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 10,
    minWidth: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  countBadgeText: {
    fontSize: 10,
    color: Colors.white,
    fontWeight: "700",
  },
  purchasesGrid: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 10,
    justifyContent: "center",
  },
  purchasesWrap: {
    gap: 12,
  },
  purchaseItem: {
    alignItems: "center",
    gap: 8,
    width: 80,
  },
  purchaseItemBottom: {
    alignItems: "center",
    gap: 8,
    width: 80,
  },
  bottomPurchaseRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  purchaseIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  itemCountBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: Colors.error,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  itemCountBadgeText: {
    fontSize: 9,
    color: Colors.white,
    fontWeight: "700",
    lineHeight: 11,
  },
  purchaseLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: Colors.text,
  },
  referralValue: {
    fontSize: 13,
    fontWeight: "800",
    color: Colors.text,
    marginTop: -2,
  },

  // ── My Referrals ──
  referralsGrid: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 0,
    justifyContent: "space-around",
    alignItems: "center",
  },
  referralItem: {
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  referralIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  referralItemValue: {
    fontSize: 13,
    fontWeight: "800",
    color: Colors.text,
  },
  referralItemLabel: {
    fontSize: 12,
    fontWeight: "500",
    color: Colors.textSecondary,
  },

  // ── QR Section ──
  qrSubtitle: {
    fontSize: 12,
    color: Colors.sky,
    fontWeight: "600",
    marginTop: 2,
  },
  qrContainer: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 20,
  },
  qrCard: {
    borderRadius: radius.lg,
    padding: 16,
    borderWidth: 1,
  },
  qrCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  },
  qrIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  qrCardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
  },
  qrCardDescription: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginBottom: 16,
    lineHeight: 16,
  },
  qrTopLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.sky,
    marginBottom: 12,
    marginLeft: 16,
    marginRight: 16,
  },
  qrMain: {
    flexDirection: "row",
    gap: 16,
    alignItems: "center",
    marginBottom: 16,
  },
  qrImageWrapper: {
    width: 100,
    height: 100,
    padding: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    alignItems: "center",
    justifyContent: "center",
  },
  qrImage: {
    width: 80,
    height: 80,
  },
  qrImageTag: {
    position: "absolute",
    bottom: -8,
    backgroundColor: Colors.sky,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  qrImageTagText: {
    color: Colors.white,
    fontSize: 8,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  qrInfo: {
    flex: 1,
    gap: 4,
  },
  qrLabel: {
    fontSize: 10,
    color: Colors.textSecondary,
    fontWeight: "500",
  },
  qrLinkBox: {
    padding: 8,
    borderRadius: 8,
    marginTop: 4,
    borderWidth: 1,
    borderStyle: "dashed",
  },
  qrLinkText: {
    fontSize: 10,
    color: Colors.sky,
    fontWeight: "600",
  },
  qrActions: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    marginTop: 8,
  },
  qrSeparator: {
    height: 1,
    backgroundColor: "#e2e8f0",
    marginHorizontal: 8,
  },

  // ── Menu ──
  section: {
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: "hidden",
    ...shadow.sm,
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
  },
  menuRowBorder: {
    borderBottomWidth: 1,
  },
  menuIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  menuIconDanger: {
    backgroundColor: "#fee2e2",
  },
  menuLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    color: Colors.text,
  },
  menuLabelDanger: {
    color: Colors.error,
  },

  // ── Modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    maxWidth: 380,
    width: "100%",
  },
  modalCloseBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  modalQrImage: {
    width: 280,
    height: 280,
    marginTop: 16,
    marginBottom: 20,
  },
  modalQrUrl: {
    fontSize: 12,
    color: Colors.textSecondary,
    fontWeight: "500",
    textAlign: "center",
    marginBottom: 4,
  },

  // ── Profile Details Overlay ──
  profileDetailsOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    backgroundColor: Colors.white,
  },

  // ── Google Link Banner ──
  googleLinkBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: Colors.sky,
    gap: 10,
  },
  googleLinkContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  googleLinkText: {
    flex: 1,
    gap: 0,
  },
  googleLinkTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1e40af",
  },
  googleLinkSubtitle: {
    fontSize: 10,
    fontWeight: "400",
    color: "#1e3a8a",
    opacity: 0.8,
  },
  googleLinkBtn: {
    backgroundColor: Colors.sky,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  googleLinkBtnText: {
    fontSize: 11,
    fontWeight: "600",
    color: Colors.white,
  },

  // ── Security Banner ──
  securityBannerNew: {
    borderRadius: 8,
    borderWidth: 1,
    borderLeftWidth: 4,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  securityBannerCloseNew: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  securityBannerMainContent: {
    flex: 1,
    gap: 4,
    marginRight: 24,
  },
  securityBannerIconTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  securityBannerTitleNew: {
    fontSize: 13,
    fontWeight: "700",
  },
  securityBannerSubtitleNew: {
    fontSize: 11,
    fontWeight: "400",
    lineHeight: 14,
  },
  securityBannerActionBtn: {
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  securityBannerActionBtnText: {
    fontSize: 12,
    fontWeight: "700",
    color: Colors.white,
  },

  // ── Wallet Section ──
  walletCardsContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 0,
  },
  walletSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingBottom: 12,
    borderBottomWidth: 1,
    marginBottom: 12,
  },
  walletSectionTitle: {
    fontSize: 14,
    fontWeight: "700",
  },
  walletCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    padding: 14,
    overflow: "hidden",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  walletCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  walletCardTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  walletIconChip: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  walletCardTitleText: {
    fontSize: 14,
    fontWeight: "700",
  },
  walletCardContent: {
    marginTop: 12,
    gap: 10,
  },
  walletStatRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  walletStatLabel: {
    fontSize: 12,
    fontWeight: "500",
  },
  walletStatValue: {
    fontSize: 13,
    fontWeight: "700",
  },
  walletCardFooterText: {
    fontSize: 10,
    fontWeight: "400",
    lineHeight: 14,
  },

  // ── PV Overview Section ──
  pvOverviewSection: {
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: "hidden",
    ...shadow.sm,
  },
  pvStatsRow: {
    flexDirection: "row",
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  pvStatItem: {
    flex: 1,
    alignItems: "center",
  },
  pvStatLabel: {
    fontSize: 11,
    fontWeight: "600",
    marginBottom: 4,
  },
  pvStatValue: {
    fontSize: 16,
    fontWeight: "800",
  },
  pvStatDivider: {
    width: 1,
    height: 40,
    marginHorizontal: 12,
  },
  leaderboardRankDisplay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  referralsDisplay: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  dailyCheckinBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    gap: 8,
  },
  dailyCheckinBtnLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  dailyCheckinBtnText: {
    fontSize: 13,
    fontWeight: "600",
  },
  dailyCheckinIconContainer: {
    position: "relative",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  dailyCheckinBadge: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#ff4444",
  },
  dailyCheckinIcon: {
    width: 20,
    height: 20,
  },
  walletCardIcon: {
    width: 20,
    height: 20,
  },
  dailyCheckinClaimContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  dailyCheckinDotContainer: {
    position: "relative",
    width: 12,
    height: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  dailyCheckinDotGlow: {
    position: "absolute",
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: Colors.error + "25",
  },
  dailyCheckinRedDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.error,
  },
  dailyCheckinClaimText: {
    fontSize: 13,
    fontWeight: "700",
    color: Colors.sky,
  },
})
