import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  qrInstructions: {
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 12,
    textAlign: "center",
  },
  headerBackground: {
    position: "relative",
    overflow: "hidden",
    minHeight: 90,
    borderBottomWidth: 1,
  },
  headerBackgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  headerContent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingBottom: 8,
  },
  headerIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: Colors.white,
    flex: 1,
    textAlign: "center",
  },
  content: {
    padding: 8,
    gap: 8,
    paddingBottom: 16,
  },
  section: {
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
  },
  sectionTitle: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sectionTitleText: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 2,
  },
  sectionTitleDescription: {
    fontSize: 13,
    marginTop: 4,
  },
  inputGroup: {
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
    marginBottom: 6,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  input: {
    flex: 1,
    fontSize: 14,
    padding: 0,
  },
  button: {
    flexDirection: "row",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 16,
    marginBottom: 16,
  },
  buttonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  emptyText: {
    fontSize: 13,
    textAlign: "center",
    paddingVertical: 16,
  },
  dangerSection: {
    borderColor: "#fecaca",
    marginBottom: 32,
  },
  dangerText: {
    color: "#ef4444",
  },
  dangerButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#fee2e2",
  },
  dangerButtonContent: {
    flex: 1,
  },
  dangerButtonLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ef4444",
  },
  dangerButtonDescription: {
    fontSize: 12,
    marginTop: 2,
  },
  passkeyDate: {
    fontSize: 12,
    marginTop: 2,
  },
  accountItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderRadius: 8,
    marginHorizontal: 16,
    marginBottom: 12,
  },
  accountItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  accountIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  accountName: {
    fontSize: 14,
    fontWeight: "600",
  },
  accountEmail: {
    fontSize: 12,
    marginTop: 2,
  },
  accountStatus: {
    alignItems: "flex-end",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "600",
  },
  passkeyDate: {
    fontSize: 12,
    marginTop: 2,
  },
  accountActionsContainer: {
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  accountButton: {
    flexDirection: "row",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  accountButtonText: {
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  qrCamera: {
    height: 300,
    marginHorizontal: 16,
    marginVertical: 12,
    borderRadius: 8,
    borderWidth: 1,
    overflow: "hidden",
    position: "relative",
  },
  qrScannerOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  qrScanFrame: {
    width: 250,
    height: 250,
    borderWidth: 2,
    borderColor: "#0ea5e9",
    borderRadius: 12,
    position: "relative",
    backgroundColor: "rgba(14, 165, 233, 0.05)",
  },
  qrCorner: {
    position: "absolute",
    width: 30,
    height: 30,
    borderWidth: 3,
    borderColor: "#0ea5e9",
  },
  qrTopLeft: {
    top: -2,
    left: -2,
    borderRightWidth: 0,
    borderBottomWidth: 0,
  },
  qrTopRight: {
    top: -2,
    right: -2,
    borderLeftWidth: 0,
    borderBottomWidth: 0,
  },
  qrBottomLeft: {
    bottom: -2,
    left: -2,
    borderRightWidth: 0,
    borderTopWidth: 0,
  },
  qrBottomRight: {
    bottom: -2,
    right: -2,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  qrInstructions: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 20,
    textAlign: "center",
  },
  permissionText: {
    fontSize: 13,
    textAlign: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  sessionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
  },
  sessionItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  sessionIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  sessionDevice: {
    fontSize: 14,
    fontWeight: "600",
  },
  sessionBrowser: {
    fontSize: 12,
    marginTop: 2,
  },
  sessionTime: {
    fontSize: 11,
    marginTop: 2,
  },
  sessionButton: {
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
})

export default styles
