import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  customHeader: {
    paddingTop: 28,
    paddingBottom: 0,
    position: "relative",
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: "hidden",
  },
  headerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    marginTop: 12,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 8,
    marginTop: 8,
  },
  searchWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 12,
    height: 40,
    backgroundColor: "transparent",
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  searchIconLeft: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    paddingVertical: 0,
  },
  clearSearchButton: {
    marginLeft: 6,
  },
  filterIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "transparent",
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  backIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: "transparent",
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  brandHeaderContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  brandLogoHeader: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#cbd5e1",
  },
  brandLogoImageHeader: {
    width: "100%",
    height: "100%",
    resizeMode: "contain",
  },
  brandLogoFallbackHeader: {
    width: "100%",
    height: "100%",
    backgroundColor: Colors.sky,
    alignItems: "center",
    justifyContent: "center",
  },
  brandInitialHeader: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.white,
  },
  brandHeaderText: {
    flex: 1,
  },
  brandNameRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  brandHeaderLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.sky,
    lineHeight: 13,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  brandHeaderName: {
    fontSize: 16,
    fontWeight: "700",
    color: Colors.text,
    lineHeight: 18,
    marginBottom: 6,
  },
  brandHeaderSupplier: {
    fontSize: 12,
    color: Colors.textSecondary,
    lineHeight: 14,
  },
  brandHeaderTagline: {
    fontSize: 11,
    color: Colors.textSecondary,
    lineHeight: 13,
    fontStyle: "italic",
  },
  brandMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 1,
  },
  brandMetaDot: {
    fontSize: 9,
    color: Colors.textSecondary,
  },
  brandHeaderProducts: {
    fontSize: 11,
    color: Colors.textSecondary,
    marginTop: 0,
    lineHeight: 13,
  },
  topFollowButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 18,
  },
  topFollowButtonText: {
    fontSize: 11,
    fontWeight: "700",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 8,
    gap: 8,
    paddingBottom: 16,
  },
  tabBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 0,
    paddingBottom: 0,
    marginHorizontal: 0,
    marginTop: 10,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderTopWidth: 0,
  },
  tabItem: {
    flex: 1,
    paddingVertical: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#9ca3af",
  },
  tabTextActive: {
    color: Colors.sky,
  },
  tabIndicator: {
    width: "80%",
    height: 2.5,
    marginTop: 2,
    borderRadius: 1.5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
  },
  menuContainer: {
    position: "absolute",
    right: 12,
    backgroundColor: Colors.white,
    borderRadius: 12,
    minWidth: 180,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  menuIcon: {
    marginRight: 12,
  },
  menuText: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.text,
  },
  menuDivider: {
    height: 1,
    backgroundColor: "#e5e7eb",
  },
})

export default styles
