import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#000" },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  container: { flex: 1, justifyContent: "center", alignItems: "center" },
  spacer: { flex: 1 },
  gradient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  contentSection: {
    paddingHorizontal: 16,
    gap: 12,
    zIndex: 2,
    width: "100%",
  },
  card: {
    height: "88%",
    maxHeight: 760,
    minHeight: 560,
    flexShrink: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  backButton: { alignSelf: "flex-start", padding: 8, marginBottom: 12 },
  header: { flexShrink: 0 },
  logo: { width: 160, height: 56, alignSelf: "center", marginBottom: 24 },
  tabs: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    height: 38,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: { backgroundColor: Colors.sky },
  tabText: {
    fontSize: 14,
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.7)",
  },
  tabTextActive: { color: Colors.white },
  heading: {
    fontSize: 24,
    fontWeight: "800",
    color: Colors.white,
    marginBottom: 4,
  },
  subheading: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.9)",
    marginBottom: 16,
  },
  formScrollContent: { paddingBottom: 12 },
  fieldRow: { flexDirection: "row", gap: 12 },
  fieldWrap: { width: "100%", marginBottom: 14 },
  halfField: { flex: 1, marginBottom: 0 },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "rgba(255, 255, 255, 0.9)",
    marginBottom: 6,
  },
  required: { color: "#ff6b6b" },
  input: {
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    paddingHorizontal: 14,
    fontSize: 15,
    color: Colors.white,
  },
  inputError: { borderColor: "#ff6b6b" },
  hint: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.7)",
    marginTop: 5,
    marginLeft: 2,
  },
  ruleList: { marginTop: 6, marginLeft: 4, gap: 3 },
  ruleText: { fontSize: 11, color: "rgba(255, 255, 255, 0.7)" },
  errorText: { fontSize: 12, color: "#ff6b6b", marginTop: 5, marginLeft: 2 },
  passwordRow: {
    flexDirection: "row",
    alignItems: "center",
    height: 48,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    paddingLeft: 14,
    paddingRight: 12,
  },
  passwordInput: { flex: 1, fontSize: 15, color: Colors.white },
  termsBox: {
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  checkboxRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.3)",
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  checkboxChecked: { backgroundColor: Colors.sky, borderColor: Colors.sky },
  termsText: { flex: 1, fontSize: 12, color: "rgba(255, 255, 255, 0.9)" },
  linkText: { color: Colors.sky, fontWeight: "700" },
  signUpBtn: { borderRadius: 10, backgroundColor: Colors.sky },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  termsModalContent: {
    width: "100%",
    maxWidth: 520,
    maxHeight: "86%",
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 20,
  },
  termsModalTitle: { fontSize: 22, fontWeight: "800", color: Colors.text },
  termsModalSubtitle: {
    marginTop: 6,
    marginBottom: 14,
    color: Colors.textSecondary,
    fontSize: 13,
  },
  termsModalScroll: { maxHeight: 420 },
  termsModalScrollContent: { paddingBottom: 12 },
  termsParagraphTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: Colors.text,
    marginTop: 10,
    marginBottom: 6,
  },
  termsParagraph: {
    fontSize: 13,
    lineHeight: 19,
    color: Colors.text,
    marginBottom: 8,
  },
  termsModalFooter: { flexDirection: "row", gap: 10, marginTop: 8 },
  termsCloseBtn: {
    flex: 1,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.inputBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  termsCloseBtnText: { color: Colors.text, fontWeight: "700" },
  termsAcceptBtn: {
    flex: 1,
    height: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.sky,
  },
  termsAcceptBtnDisabled: { backgroundColor: "#93c5fd" },
  termsAcceptBtnText: { color: Colors.white, fontWeight: "800" },
})

export default styles
