import { StyleSheet } from "react-native"
import { Colors } from "../constants/colors"
import { palette, radius, shadow } from "../theme/theme"

const styles = StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: palette.slate50,
  },
  centerContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    paddingHorizontal: 16,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
    marginTop: 16,
  },
  emptySubtitle: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginTop: 8,
    textAlign: "center",
  },
  header: {
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 12,
    ...shadow.sm,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  titleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  headerLogo: {
    // Square brand mark (1024×1024) — keep the box square.
    width: 64,
    height: 64,
  },
  screenTitle: {
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: -0.4,
    color: Colors.text,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  headerBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  headerBadgeText: {
    color: Colors.white,
    fontSize: 9,
    fontWeight: "800",
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  selectAllCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
  },
  selectAllCheckboxChecked: {
    backgroundColor: Colors.sky,
    borderColor: Colors.sky,
  },
  selectAllText: {
    fontSize: 12,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  selectAllTextActive: {
    color: Colors.sky,
    fontWeight: "700",
  },
  filterSection: {
    flexDirection: "row",
    gap: 6,
  },
  filterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: radius.full,
    backgroundColor: "#f3f4f6",
    borderWidth: 0,
  },
  filterBtnActive: {
    backgroundColor: Colors.sky,
  },
  filterText: {
    fontSize: 11,
    fontWeight: "700",
    color: Colors.text,
  },
  filterTextActive: {
    color: Colors.white,
    fontWeight: "700",
  },
  listContent: {
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: 24,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingHorizontal: 14,
    height: 46,
  },
  searchBarFocused: {
    borderColor: Colors.sky,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: "500",
    paddingVertical: 0,
  },
  rowWrap: {
    borderRadius: radius.lg,
    borderWidth: 1,
    overflow: "hidden",
    marginBottom: 10,
    ...shadow.sm,
  },
  rowActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  rowActionCart: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: Colors.sky,
    paddingVertical: 9,
    borderRadius: radius.md,
  },
  rowActionCartText: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: "700",
  },
  rowActionDelete: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 9,
    paddingHorizontal: 18,
    borderRadius: radius.md,
    borderWidth: 1.5,
  },
  rowActionDeleteText: {
    color: "#ef4444",
    fontSize: 13,
    fontWeight: "700",
  },
  listFooter: {
    paddingVertical: 20,
    alignItems: "center",
  },
  listStateBox: {
    paddingTop: 90,
    paddingHorizontal: 24,
    alignItems: "center",
    gap: 12,
  },
  footer: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
  },
  totalSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  totalLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colors.textSecondary,
  },
  totalPrice: {
    fontSize: 18,
    fontWeight: "800",
    color: Colors.text,
  },
  checkoutBtn: {
    backgroundColor: Colors.sky,
    paddingVertical: 14,
    borderRadius: radius.lg,
    alignItems: "center",
    ...shadow.sm,
  },
  checkoutBtnText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "700",
  },
  rowBack: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    overflow: "hidden",
  },
  backLeftBtn: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 90,
  },
  backLeftBtnLeft: {
    backgroundColor: Colors.sky,
    left: 0,
  },
  backRightBtn: {
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 90,
  },
  backRightBtnRight: {
    backgroundColor: "#ef4444",
    right: 0,
  },
  cartActionInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    width: 90,
  },
  deleteActionInner: {
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    width: 90,
  },
  backTextWhite: {
    color: Colors.white,
    fontSize: 10,
    fontWeight: "800",
    textAlign: "center",
  },
  swipeHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#f9fafb",
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  swipeHintText: {
    fontSize: 10,
    color: Colors.textSecondary,
    letterSpacing: 0.3,
  },
})

export default styles
